[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/nicokoch/reflink"]
git = "https://github.com/nicokoch/reflink"
rev = "e8d93b465f5d9ad340cd052b64bbc77b8ee107e2"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
